### ISSUE TITLE
Hiera 5 Support is bad

### ISSUE THREAD

**Issue by dylanratcliffe** [dylanratcliffe/onceover#100]
Hiera 5 works a bit differently. If you have a hiera.yaml under the spec directory, it is not respected and uses the main one. This is unlikely to be expected, it should use the one under spec. However it also needs a path relative to the hiera.yaml, instead of being relative to the root of the controlrepo as in hiera 3

**Comment by sandymcp** [comment]
The fix for this breaks the way 3.2.0 worked. We are still using puppet 4.7.0, which changes do I need to make to get this working with the new version.
