### ISSUE TITLE
Uninformative error when hiera.yaml is missing

### ISSUE THREAD

**Issue by TraGicCode** [dylanratcliffe/onceover#104]
When you are missing a hiera.yaml at the root of the control-repo or even in the /spec folder you recieve an uninformative error message indicating the problem is the missing file. 

![image](https://user-images.githubusercontent.com/6224270/28750526-bfed256c-74b3-11e7-9f9f-864f3e517f42.png)

Is the hiera.yaml file a requirement to exist for onceover to be able to do it's work?

**Comment by dylanratcliffe** [comment]
Shouldn't be. This might be a regression from a recent change I did. Can you please re-run with --trace?
