### ISSUE TITLE
Deprecation warnings for hiera functions are breaking all tests when hiera functions used

### ISSUE THREAD

**Issue by GeoffWilliams** [dylanratcliffe/onceover#107]
The recent deprecation warnings in Puppet that warn:

```
        "The function '#{self.class.name}' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/#{Puppet.minor_version}/reference/deprecated_language.html")
```

Cause complete test failure when running onceover in code that uses functions such as `hiera_hash(...)`:

```
Failures:

  1) role::obsidian::client using fact set projectx.au.megacorp.com should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }
       error during compilation: Evaluation Error: Error while evaluating a Function Call, undefined method `minor_version' for Puppet:Module at /vagrant/control_repo/.onceover/etc/puppetlabs/code/environments/production/modules/sudo/manifests/configs.pp:20:14 on node localhost.localdomain
     # ./spec/classes/role__obsidian__client_on_projectx.au.megacorp.com_spec.rb:7:in `block (3 levels) in <top (required)>'
```

In this case, it's the saz/sudo module using the `hiera_hash()` function which triggers the error.  Searching the system for `minor_version` we can see its puppet itself causing this error, which is triggered in the file `puppet-4.10.5/lib/hiera/puppet_function.rb`.  Using pry, we can see that `minor_version` is indeed not available:

```
[1] pry(#<#<Class:0x00000004fe7118>>)> Puppet.version
=> "4.7.1"
[2] pry(#<#<Class:0x00000004fe7118>>)> Puppet.minor_version
NoMethodError: undefined method `minor_version' for Puppet:Module
from (pry):2:in `lookup'
```

Changing `Puppet` to `::Puppet` doesn't fix the error - at this point its not clear what the exact cause of the problem is - perhaps something else needs to be loaded?

## Workaround
Use an earlier version of the `puppet` gem that doesn't have the deprecation message.  In your control repository's `Gemfile` add (or replace any existing declaration):

```
gem 'puppet', '4.7.1'
```

Then install the gem and rerun tests:

```
bundle update
bundle exec rake spec
```

Tests should now be passing:

```
role::obsidian::client
  using fact set projectx.au.megacorp.com
    should compile into a catalogue without dependency cycles
```

## Analysis
Doesn't seem to be onceover (or even puppet-rspec's) fault - recommend documentation about setting a version of puppet in the Gemfile or setting a version that will work when doing `onceover init`.  Puppet 5.x also exhibits this error since the same message is present

**Comment by dylanratcliffe** [comment]
@GeoffWilliams I can't replicate this at all using `hiera_hash('foo',{})` with Puppet 4.7.0 or 5.1.0. Also it's hard to see how it would have happened given that it's an error coming from the Puppet gem, calling something else in the Puppet gem.

**Comment by GeoffWilliams** [comment]
@dylanratcliffe I think this ended up being some strange combination of tests/libraries because of some old rspec tests the customer was also wanting to run.  I ended up having to upgrade puppet anyway because hiera was busted ... :man_shrugging:   I think we've captured enough in this ticket to help any poor souls who suffer the same fate - closing
