### ISSUE TITLE
Templated .file removed at some point

### ISSUE THREAD

**Issue by claw-real** [dylanratcliffe/onceover#115]
We have a templated file called .conkyrc.erb.  Something in the onceover processing is removing that from .onceover/etc/puppetlabs/code/environments/production/site/profile/templates/conky so all catalog compilation fails.  
Geoff Williams knows more about the exact issue, and the setup of onceover.

**Comment by dylanratcliffe** [comment]
This is likely something to do with the way Ruby is globbing the directories, skipping hidden files. If you are interested in creating a PR i'd start investigating here: https://github.com/dylanratcliffe/onceover/blob/master/lib/onceover/testconfig.rb#L201

If not I'll get to it when I can

**Comment by GeoffWilliams** [comment]
Suggest linking this in with #113 and #95 if these are going to result in a significant alteration
