### ISSUE TITLE
Onceover needs its own acceptance tests

### ISSUE THREAD

**Issue by jessereynolds** [dylanratcliffe/onceover#116]
Onceover needs its own acceptance tests, and possibly unit tests too

**Comment by Mandos** [comment]
I'm going to add some simple rspec and cucumber tests soon.

**Comment by jessereynolds** [comment]
@Mandos great! ... I actually started adding simple Cucumber tests last week and hope to get a PR done shortly. It would be good to get feedback / compare approaches.

**Comment by Mandos** [comment]
@jessereynolds Could you look at #134?

**Comment by dylanratcliffe** [comment]
This still needs a lot of expansion but @Mandos and @jessereynolds have given us a great start. Closing this ticket
