### ISSUE TITLE
Onceover does not generate nodesets

### ISSUE THREAD

**Issue by x4FF3** [dylanratcliffe/onceover#120]
Hi,

as i started today with onceover, it does not generate the acceptance folder nor the nodesets.
`bash
$ bundle exec onceover init --trace
created spec
created spec/onceover.yaml
created spec/pre_conditions
created spec/pre_conditions/README.md
created spec/factsets
created spec/factsets/README.md
created Rakefile
skipped Gemfile (exists)
`

**Comment by dylanratcliffe** [comment]
Hey, the reason it's not doing this is onceover has been updated to deprecate the acceptance testing capability in [this commit](https://github.com/dylanratcliffe/onceover/commit/3131fb1ee6258f2b750c01e57be796604321b42a). It was really janky and hard to debug. Hopefully I will be implementing some plugins that re-implement that functionality but that is lower on the priority list for now.

**Comment by philomory** [comment]
Might I recommend removing the bits about acceptance testing and nodesets from the README in that case? I spent a fair bit of time going down this rabbithole before I discovered this issue, and I'm sure others have as well.
