### ISSUE TITLE
Issue Running onceover on Windows 10 

### ISSUE THREAD

**Issue by jweaver4** [dylanratcliffe/onceover#143]
I receive this error when executing onceover on Windows 10 ...
role::apache using fact set RedHat-7.4-64 should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }
       error during compilation: Evaluation Error: Error while evaluating a Function Call, Could not find class ::role::apache for .localdomain at line 2:1 on node .localdomain
This error occurs for every class I believe it has to do with Windows' paths, but am unable to track it down.  This runs fine on Linux for non-windows roles.  Has anyone had success executing onceover on the Windows platform? Thanks.

**Comment by philomory** [comment]
So I can expand on this: the generated spec_helper.rb contains the line
`c.module_path = 'C:/code/puppet/.onceover/etc/puppetlabs/code/environments/production/site:C:/code/puppet/.onceover/etc/puppetlabs/code/environments/production/modules'`

Puppet and Onceover think `:` is a separator for multiple paths, here, but of course in Windows it means something very different. Replaceing the `:` with a `;` resolves the problem if you run rspec manually, but running `onceover run spec` regenerates spec_helper.rb and breaks it again.
