### ISSUE TITLE
Doesn't work out-of-the-box with Puppet's ruby

### ISSUE THREAD

**Issue by dan-wittenberg** [dylanratcliffe/onceover#147]
puppet-agent 5.3.3
# which gem
/opt/puppetlabs/puppet/bin/gem

# gem install onceover
....
$ onceover
/opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'puppet' (>= 0) among 219 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/dwittenberg/.gem/ruby/2.4.0:/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0', execute `gem env` for more information
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/specification.rb:1444:in `block in activate_dependencies'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/specification.rb:1433:in `each'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/specification.rb:1433:in `activate_dependencies'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/specification.rb:1415:in `activate'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/specification.rb:1447:in `block in activate_dependencies'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/specification.rb:1433:in `each'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/specification.rb:1433:in `activate_dependencies'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/specification.rb:1415:in `activate'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems.rb:300:in `block in activate_bin_path'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems.rb:300:in `synchronize'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems.rb:300:in `activate_bin_path'
        from /opt/puppetlabs/puppet/bin/onceover:23:in `<main>'

# gem list ^puppet

*** LOCAL GEMS ***

puppet (5.3.3)
....

**Comment by dylanratcliffe** [comment]
Hey @dan-wittenberg, Onceover is tested against Ruby 2.4.2, which comes with Puppet 5.3.3 and everything does work. While it should theoretically be possible to install and run onceover from within the Puppet gem environment, it's definitely not recommended as there will be conflicts between gem executables and Puppet native ones.

My recommendation is to use [rbenv](https://github.com/rbenv/rbenv) to manage your ruby environment and [bundler](http://bundler.io/) to manage gems, much less chance of conflict and you won't pollute/break your vendored Puppet environment.

I tried to get this working myself and ran into a bunch of issues, mostly with r10k which seem to have to do with conflicts in the Puppet ruby environment, it's much easier and more reliable to just use rbenv/bundler. Closing for now as it's not actually an issue with onceover

**Comment by dan-wittenberg** [comment]
Too bad, there's a lot of environments where you only get what comes with
Puppet, so more advanced management isn't possible.  I was hoping to use
this for many more clients, guess will find another solution but thanks for
looking!

Dan
