### ISSUE TITLE
`mock_with` deprecation warnings

### ISSUE THREAD

**Issue by ardrigh** [dylanratcliffe/onceover#174]
We have been testing setting up onceover on our control repo, and in the output the deprecation warning appears:

```ruby
gem 'onceover'
```

```ruby
Deprecation Warnings:

puppetlabs_spec_helper: defaults `mock_with` to `:mocha`. See https://github.com/puppetlabs/puppetlabs_spec_helper#mock_with to choose a sensible value for you
```

I don't see anywhere in the documentation mention of a `spec_helper.rb` apart from reference to custom templates. Is that the only way to configure onceover `mock_with` to use `:rspec`?

**Comment by dylanratcliffe** [comment]
At the moment yes. This should be rectified though as it's deprecated
