### ISSUE TITLE
Doubled up results in output of 'run spec'

### ISSUE THREAD

**Issue by jessereynolds** [dylanratcliffe/onceover#180]
Happens in 3.7.0 and 3.8.0

eg:

```
...
Finished in 0.8986 seconds (files took 1.3 seconds to load)
1 example, 0 failures

Finished in 0.8986 seconds (files took 1.3 seconds to load)
1 example, 0 failures
```

This is reproduceable by running `bundle exec onceover run spec` in the following control-repo at this specific version (current HEAD): https://github.com/jessereynolds/control-repo-fbz/tree/0d0c9ba51fc83c19507bb74712e7702db7b8a8a2

**Comment by dylanratcliffe** [comment]
Fixed in `3.10.0`
