### ISSUE TITLE
Remove acceptance testing from README

### ISSUE THREAD

**Issue by matikij** [dylanratcliffe/onceover#186]
As running acceptance tests is deprecated (and doesn't seem to be working with current beaker) please remove or at least notify the reader that beaker is not supported in onceover.

**Comment by dylanratcliffe** [comment]
@matikij Are you able to submit a PR for this? I totally agree and will approve the PR straight away

**Comment by GeoffWilliams** [comment]
@dylanratcliffe PR done 🍺
