### ISSUE TITLE
Unable to install onceover gem on windows due to symlink in r10k

### ISSUE THREAD

**Issue by jessereynolds** [dylanratcliffe/onceover#204]
The r10k ruby gem is unable to be installed on Windows since version 2.6.3 as per https://github.com/puppetlabs/r10k/issues/833 

r10k is a dependency of onceover so trying to install the onceover ruby gem fails at the point it tries to install r10k: 

```
ERROR:  While executing gem ... (Errno::EACCES)
	Permission denied @ rb_file_s_symlink - (integration, C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/r10k-3.1.1/test)
```

**Comment by jessereynolds** [comment]
Yep - should be linked here

**Comment by dylanratcliffe** [comment]
This is merged upstream now! YAY!
