### ISSUE TITLE
FYI - speedup `r10k puppetfile install` with g10k

### ISSUE THREAD

**Issue by johnwarburton** [dylanratcliffe/onceover#234]
Hi  @dylanratcliffe and @GeoffWilliams

This is a speedup FYI - not sure where to put it...

Thanks for onceover - a very cool tool @GeoffWilliams introduced us to. I am hooking onceover into our CI system and on new PRs and merges, a whole new copy of modules needs to be deployed via r10K. This can be quite tedious as have made great progress speeding it up with the nice `parallel` option

I have had some success using [g10k](https://github.com/xorpaul/g10k/) prepping the control repo. g10k isn't a drop in replacement and doesn't like the forge directive or module names with hyphens that are in git ([assumes they are from the forge](https://github.com/xorpaul/g10k/issues/46)), but it does locally cache modules, which means setup is ~5 seconds, and not a couple of minutes

There is some jiggery pokery but it gets me to where I need as this needs to happen after deploy.rb but there's no easy way to jump in. Here's what our makefile looks like for spec tests
```
ONCEOVER_DIR=.onceover/etc/puppetlabs/code/environments/production

	mkdir -p ${ONCEOVER_DIR} && \
	sed -e '/^forge/d' -e 's#saz-rsyslog#saz/rsyslog#' -e 's#martyewings-agent_run_with_tags#martyewings/agent_run_with_tags#' Puppetfile.onceover > ${ONCEOVER_DIR}/Puppetfile.g10k && \
	cd .onceover/etc/puppetlabs/code/environments/production && \
	/usr/local/bin/g10k -usemove -puppetfile -puppetfilelocation ./Puppetfile.g10k 
	bundle exec onceover run spec --skip_r10k --puppetfile Puppetfile.onceover --parallel --format documentation
```
Regards

John

**Comment by GeoffWilliams** [comment]
Hey John!

I've used a local forge in the past (artifactory pro) which has given a massive speedup. I've also hacked around with a `../modules` directory full of checked out modules from git which can then be copied into onceover via `Makefile` like this:

```
onceover:
	# assumes you have all required modules checked out at ../modules - COPY
	# them all to `site` which is in the modulepath so that our local modules
	# can be found. needed because R10K and onceover dont support local modules
	# and/or symlinks at the module level
	# check all syntax + lint
	bundle exec onceover run codequality --no_docs
	PATH=spec/mock:$$PATH bundle exec onceover run spec --puppetfile Puppetfile.onceover

# useful to fix too many levels of symlinks error after running PDK
clean:
	rm -rf .onceover
```

For me, this was a really easy and fast way to work with modules on a workstation where stuff is under active development - appreciate this might not be that useful to you. Onceover does do some caching of downloaded modules but I bet these are being lost between test runs in your CI environment. If your containerised it might be worth finding the cache and making it a volume. There is also an `r10k.conf` file you can create to configure a global cache too - depending how far down the rabbit hole you want to go.

The extract you shared looks pretty good - I looked at the g10k issue you shared and there's a workaround in there. I would probably handle this by saying to remove the hyphen from forge modules downloaded from git (never even noticed this was allowed before):

```
mod "rsyslog",
  :git => "https://github.com/saz/puppet-rsyslog",
  :ref => "DEADBEEFDEADBEEF"
```

This stanza would be correctly deployed by both `r10k`/Code Manager and `g10k`. Failing that your options are `sed` tricks or fixing `g10k` to account for the longer syntax.

`g10k` detection and use might be a cool onceover speedup too but like you said there are subtle differences at the moment.

**Comment by johnwarburton** [comment]
Hi @GeoffWilliams 

Thanks for taking a look

We just got Artifactory Pro, but are a little way off using it to mirror forge modules, but yes that is the simplest choice

As you say - the hack you suggested isn't going to work too well, and containerizing the CI is even more work!

The only reason we have hyphens in module names is for local forks of forge modules while waiting for PRs to be looked at, so may be confusing when we go back, but that will be probably what we will do. Swings and roundabouts

Would be great even if r10k could download in parallel, the issue isn't seen as important
* https://github.com/puppetlabs/r10k/issues/54
* https://tickets.puppetlabs.com/browse/RK-298

**Comment by dylanratcliffe** [comment]
@johnwarburton r10k can download in parallel! (as of very, very recently) and I agree that the clone time is a huge, huge pain in the ass. This PR: https://github.com/dylanratcliffe/onceover/pull/226 implements support for adding an r10k config file which lets you set the number of threads. I've tested it on Mac and it's amazing but it's failing tests on Windows but I haven't been able to work out why. If you can point me at what's going on I'll fix it and release the new functionality which will solve your problem

**Comment by johnwarburton** [comment]
Hi @dylanratcliffe 

Thanks for taking a look at this. Our use case in in a Jenkins CI pipeline so we need onceover to run very quickly. 

The fact you can use r10k pulling stuff down in parallel is good (better than before), but the caching of forge module downloads is what I am looking for. If PR #226 allows a fully working r10k config file, then it might help, but documentation around R10K caching is thin and somewhat confusing as to what is supported (https://tickets.puppetlabs.com/browse/RK-61, https://github.com/puppetlabs/r10k/pull/729). g10k caches the tgz as well as unpacked tgz so I would have to test timings, but at the moment, g10k is "blindingly fast"

**Comment by dylanratcliffe** [comment]
r10k should now be able to run in parallel by placing the following in `spec/r10k.yaml`:

```yaml
---
pool_size: 10
```

This requires [3.16.0](https://github.com/dylanratcliffe/onceover/releases/tag/v3.16.0) As per the [r10k docs](https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#pool_size)

**Comment by johnwarburton** [comment]
Thanks @dylanratcliffe  - will take a look when I get back to work later in the week
