### ISSUE TITLE
Facter 4 gem breaks things

### ISSUE THREAD

**Issue by genebean** [dylanratcliffe/onceover#258]
https://rubygems.org/gems/facter/versions/4.0.11 busted my CI when pulled in by Puppet's requirement of less than 5. Setting my Gemfile to use Facter 2 fixed things.

**Comment by dylanratcliffe** [comment]
@genebean It runs in my CI fine. Can you please try to pul together some kind of reproduction case that I can add to my automated tests? I will merge #259 for now thugh

**Comment by genebean** [comment]
This no longer seems to be an issue and I have put up #294 to undo the pinning.
