### ISSUE TITLE
is there a way to execute only r10k step when running onceover

### ISSUE THREAD

**Issue by johnqa** [dylanratcliffe/onceover#286]
Hi, 

I am new to onceover and puppet but I am working on testing a control repo with 50+ roles.

I want to trigger onceover from a Azure Devops build, but since I cannot use --parallel (there is already an issue opened on this), I split onceover.yaml in several files and I try to run them in parallel. 
In order to shortened the test execution, I want to download all the needed modules on a single location, and then run several onceover instances (with puppet/puppet-dev-tools docker image) that point to that location.

Is there a way to have onceover only downloading the modules ( to make this a first step in the build)?

I tried to download them with a r10k command, but for some reason the execution of onceover afterwards fails.

As a workaround, currently I am executing onceover with a file having no classes defined.

Regards,
John

**Comment by dylanratcliffe** [comment]
Hey! The easitest way would be to define some tags that dont exist i.e. `--tags donttestanythingplease`. That way it won't match any tests and nothing will run, but r10k will still run

**Comment by dylanratcliffe** [comment]
I'm going to close this as I'm pretty certain it works for what you need here. But feel free to comment if that's not the case

**Comment by johnqa** [comment]
Thank you, in the meantime my workaround was to use an onceover.yaml file with no classes to test.
