### ISSUE TITLE
Error uninitialized constant RSpec::Puppet::Win32::Registry::Error running on linux env

### ISSUE THREAD

**Issue by jakeRM** [dylanratcliffe/onceover#287]
I was hoping to run onceover strictly on a linux docker container with the latest version, but I am receiving this error when I try to run it for windows servers.

```
profile::windows::chocolatey: failed
  errors:
    uninitialized constant RSpec::Puppet::Win32::Registry::Error
Did you mean?  RSpec::Puppet::Errors
               IOError
               Errno
      factsets: BIS-windows2012-baseline, BIS-windows2012-webserver, BIS-windows2016-baseline, BIS-windows2016-webserver, BIS-windows2019-baseline-jenkinsbuilder, BIS-windows2019-baseline
```

I found something online about this, which I believe might be related: https://github.com/rodjek/rspec-puppet/issues/691

I am not that well versed in the rspec code but is there anything I can do to work around this issue other then run onceover on windows?

Any help would be greatly appreciated, and I can attach any files that will help troubleshoot this.

**Comment by dylanratcliffe** [comment]
This has now been [fixed in the upstream module](https://github.com/puppetlabs/puppetlabs-chocolatey/pull/254) and should work with `puppetlabs/chocolatey` versions >= 6.0.1. If it's still failing feel free to reopen
