### ISSUE TITLE
Trusted certname uses local trusted certname

### ISSUE THREAD

**Issue by negast** [dylanratcliffe/onceover#289]
Hello

I"ve added trusted certname  as documented in the code 

`{"trusted":{"certname":"node1"},"values":{"agent_specified_environment":"production"`

https://github.com/dylanratcliffe/onceover#trusted-facts

In  our code we have a function calling 
`if $::trusted['certname'] in `

When running onceover the trusted certname is filled in with the local trusted certname instead of the one in the factset.

How can I get the function to use the one from the factset. Preferably without changing code inside the function.

**Comment by genebean** [comment]
I think I am running into this too. v3.18.1 does not show the same problem in my setup though.

**Comment by damonmaria** [comment]
I am striking the same on MacOS. Not sure if it's platform specific.
