### ISSUE TITLE
Facter changes break Onceover

### ISSUE THREAD

**Issue by dylanratcliffe** [dylanratcliffe/onceover#307]
Changes to the format of "puppet facts" has broken the ability to add new factsets to Onceover. I don't know for sure, but I imagine this will also cause problems for [https://github.com/camptocamp/facterdb] which is used by the PDK.

Here is an example of the failure in Onceover:

```
Error while running: #<NoMethodError: undefined method `delete' for nil:NilClass>/Users/geneliverman/repos/puppetlabs-modules/vendor/bundle/ruby/2.7.0/gems/onceover-3.19.1/lib/onceover/node.rb:53:in `clean_facts'
```

**Comment by dylanratcliffe** [comment]
@genebean << CC

**Comment by genebean** [comment]
Thanks @dylanratcliffe!
