### ISSUE TITLE
Support Ruby 3

### ISSUE THREAD

**Issue by genebean** [dylanratcliffe/onceover#316]
Please add support for Ruby 3 so that local testing on machines that default to it can be done.

**Comment by genebean** [comment]
The upstream project seems like it might be dormant - any thoughts on how to deal with that, assuming it is the case?

**Comment by dylanratcliffe** [comment]
Agreed. The main reason I'm using that project is that it allows for processes that you've shelled out to, to become interactive. This means that you can do things like using pry inside a function, run your onceover tests, and get dropped into a pry shell. If you use more simplistic methods the STDIN gets all borked and you can't use pry properly. I need to have a think about what the best way is to retain that functionality...

**Comment by genebean** [comment]
I certainly see the usefulness of that.

**Comment by neomilium** [comment]
The PR #326 fixes `onceover` with Ruby 3.1+.
