### ISSUE TITLE
specifying an alternate Puppetfile with --puppetfile doesn't seem to work

### ISSUE THREAD

**Issue by jessereynolds** [dylanratcliffe/onceover#39]
Running onceover like the following I would expect it to use the alternative Puppetfile I'm specifying:

```
bundle exec onceover run spec --puppetfile Puppetfile.dev
```

However it seems to just use the main Puppetfile

**Comment by dylanratcliffe** [comment]
Fixed in 3.0.3

**Comment by jessereynolds** [comment]
Thanks! Works a treat.
