### ISSUE TITLE
Properly test on windows

### ISSUE THREAD

**Issue by dylanratcliffe** [dylanratcliffe/onceover#46]

**Comment by jessereynolds** [comment]
What's the scope of this issue?

**Comment by dylanratcliffe** [comment]
Basically I haven't tested running onceover on Windows at all

**Comment by jessereynolds** [comment]
Well, the good news is that onceover seems to work fine on windows, if I use my fork of r10k that has the `test` symlink removed (see #204 and https://github.com/puppetlabs/r10k/issues/833 ). Using the following system to test on: 

- Windows 10.0.17134
- x86 - Intel Core i5-7400T CPU @ 2400 MHz, 4 Cores, 8 GB RAM
- Ruby 2.5.3p105 from RubyInstaller
- Bundler 2.0.1

It works executing in Powershell app and also Git Bash via `bundle install` and `bundle exec onceover run spec`

**Comment by dylanratcliffe** [comment]
Symplinks are removed from r10k now and onceover has full Windows acceptance tests. Closing
