### ISSUE TITLE
File resource on Windows "File paths must be fully qualified, not 'c:/foo/bar' at ... "

### ISSUE THREAD

**Issue by jessereynolds** [dylanratcliffe/onceover#59]
Seems to be caused by https://github.com/rodjek/rspec-puppet/issues/192 

```
Failures:

  1) role::bar using fact set Windows_Server-2012r2-64 should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }
       error during compilation: Parameter path failed on File[c:/inetpub/wwwroot/iisstart.htm]: File paths must be fully qualified, not 'c:/inetpub/wwwroot/iisstart.htm' at /Users/jesse/src/puppet/foo/control-repo/.onceover/etc/puppetlabs/code/environments/production/modules/iisdemo/manifests/init.pp:4
     # ./spec/classes/role__recreo_app_on_Windows_Server-2012r2-64_spec.rb:14:in `block (3 levels) in <top (required)>'

Finished in 5.06 seconds (files took 0.70679 seconds to load)
```

**Comment by jessereynolds** [comment]
Possibly the only solution for this is to have a second onceover.yaml file for the windows roles only and run this one on a Windows build server.

**Comment by dylanratcliffe** [comment]
Relates to #46

**Comment by jessereynolds** [comment]
There's now a jira ticket for this too: https://tickets.puppetlabs.com/browse/MODULES-4287

I'm also seeing this issue with the exec resource as used by the puppetlabs/chocolatey module, you get errors like this if you try and test this on posix:

```
  1) role::generic_windows using fact set Windows_Server-2008r2-64 should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }
       error during compilation: Parameter creates failed on Exec[install_chocolatey_official]: creates must be a fully qualified path at /Users/jesse/src/puppet/foo-control-repo/.onceover/etc/puppetlabs/code/environments/production/modules/chocolatey/manifests/install.pp:18
     # ./spec/classes/role__generic_windows_on_Windows_Server-2008r2-64_spec.rb:15:in `block (3 levels) in <top (required)>'
```

We need to be able to selectively stub `Puppet::Util::Platform.windows?` to return true when, eg `$facts['os']['family']` is `windows`.

**Comment by jessereynolds** [comment]
Or maybe we could stub the `absolute_path?` function, ideally replicating the actual logic but using a different test for `is windows?`

**Comment by jessereynolds** [comment]
https://github.com/rodjek/rspec-puppet/pull/498 should fix this, but merely using this version of rspec-puppet seems to not be enough. Not sure why.

**Comment by jessereynolds** [comment]
Verified that this is fixed when using rspec-puppet 2.6.7

**Comment by jessereynolds** [comment]
This is happening again with:
- rspec-puppet 2.6.15
- puppet 5.5.6
- ruby 2.4.0

and testing the puppetlabs/chocolatey module

In my onceover pre-conditions dir I've set a fake fact for choco_install_path that the chocolatey module insists must start with a drive letter, but the exec resource in chocolatey::install then uses this path and exec resource says "no, we're on POSIX, paths begin with /". Actually the result is:

```
Failures:

  1) role::basic using fact set Windows_Server-2012r2-64 should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }
       error during compilation: Parameter creates failed on Exec[install_chocolatey_official]: creates must be a fully qualified path (file: /home/jreynolds/src/puppet-control/.onceover/etc/puppetlabs/code/environments/production/modules/chocolatey/manifests/install.pp, line: 18)
     # ./spec/classes/role__basic_on_Windows_Server-2012r2-64_spec.rb:20:in `block (3 levels) in <top (required)>'
```

**Comment by jessereynolds** [comment]
Oh, ignore me. I was not using double backslashes in my `spec/pre-conditions/variables.pp` file. Once I changed all `\` to `\\` everything is golden. Ie:

```
$choco_install_path = 'c:\\foo\\bar\\choco.exe'
$chocolateyversion  = '0.9.9.8'
```
