### ISSUE TITLE
[feature] support for regenerating/updating tests

### ISSUE THREAD

**Issue by GeoffWilliams** [dylanratcliffe/onceover#61]
## Overview

I would like to be able to have onceover automatically regenerate its `onceover.yaml` file with new tests for new roles and profiles when they are added.
## Present workaround

Ensure the `spec/onceover.yaml` file is removed and prevented from being re-added via `.gitignore`.  Have your CI server run `bundle exec onceover init` as part of its build to ensure that we don't accidentally add new classes with no testing or attempt to test old classes that no longer exist.

The other onceover files for factsets, nodes, etc. are harmless and can remain in-place.
## New Feature

It would be cool to be able to run something line `onceover update` and have it update all the classes to be tested in the same vein as `onceover init`.  This would then allow the preservation of `onceover.yaml` between builds.

**Comment by dylanratcliffe** [comment]
Yeah I'm working on this at the moment by allowing people to define regexes instead of static class names? Reckon that would solve it @GeoffWilliams ?

**Comment by GeoffWilliams** [comment]
Yeah i think that would do it

On 29 September 2016 5:15:36 PM NZDT, Dylan <notifications@github.com> wrote:
>Yeah I'm working on this at the moment by allowing people to define
>regexes instead of static class names? Reckon that would solve it
>@GeoffWilliams ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanratcliffe/onceover/issues/61#issuecomment-250366368

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GeoffWilliams** [comment]
@dylanratcliffe  regex classnames fixed this

**Comment by dylanratcliffe** [comment]
Nice
