### ISSUE TITLE
[enhancement] consider making a build without beaker

### ISSUE THREAD

**Issue by GeoffWilliams** [dylanratcliffe/onceover#71]
Please consider making a build without beaker!

Beaker requires ruby >= 2.2.5 which means I couldn't test it on the internal network where I'm deployed right now.  I also couldn't run the tests from my laptop since I don't have any access to the corporate network

Unfortunately, this meant I couldn't use onceover at all :*(

**Comment by dylanratcliffe** [comment]
👎 I have thought of this too. It's planned
