### ISSUE TITLE
[feature] Puppetfile module substitution

### ISSUE THREAD

**Issue by GeoffWilliams** [dylanratcliffe/onceover#72]
So I've got a Puppetfile full of links to private copies of public modules referenced off an internal git server that I don't have access to at all.

What do you think of adding a feature where I can substitute back the public module or a local copy somehow?  Eg 

Given something like:

```
hiera,
  git => 'https://git.megacorp.com:9999/scm/puppet/hiera.git',
  ref => '2.3.0
```

I'd like to be able to easily substitute in the upstream module, maybe by a symlink?  That way I can test without changing the Puppetfile.  I think this would have to be done module-by-module rather then inferred automatically but would be very handy

**Comment by dylanratcliffe** [comment]
@GeoffWilliams You can specify a custom Puppetfile to use, would maintaining a "testing" Puppetfile work?

**Comment by GeoffWilliams** [comment]
I think that will do what I want for the moment - cool!
