### ISSUE TITLE
[enhancemant] built-in docker support

### ISSUE THREAD

**Issue by GeoffWilliams** [dylanratcliffe/onceover#8]
## Story

Doing stuff in vagrant is a pain.  Its big and slow and needs lots of memory.  I would love to be able to do my testing in Docker so that I can work much faster.  I already have a full puppet master in docker working with low memory.  If I also publish a bunch of containers with puppet agent installed too then we can just `puppet apply` to do testing right?

There's probably something that already does this too.  I would like this built-in to the Gem and with the docker images published on Docker Hub so that anyone can use them.  Will have to skip windows for the time-being though

**Comment by dylanratcliffe** [comment]
@GeoffWilliams In theory you should be able to create a nodeset file that points at docker images as per this https://github.com/puppetlabs/beaker/blob/master/docs/Docker-Support.md, as long as the image has the puppet agent installed. Can you give it a try?

**Comment by GeoffWilliams** [comment]
I wanted to do all this in docker, I really did but the problem it gives us it that It's only possible to OS's based on the same kernel as the host your running testing from.  Basically as soon as a site needs to test Windows (or AIX... or Solaris...) their going to be SOL with this approach.  While this would be cool for sites that are 100% RHEL, everyone else would have to wear the burden of either maintaining two different testing pathways - given the complexity of this, the docker approach brings diminishing returns in this instance.  On reflection, waiting it out while vagrant tests all known platforms isn't too bad - especially if we can do this in a quick and reliable way.  

closing in favour of #93
