### ISSUE TITLE
[question] Are you plan to implement support for Librarian Puppet?

### ISSUE THREAD

**Issue by Mandos** [dylanratcliffe/onceover#80]
This project looks very promising but in my company we use Librarian instead of r10k. Do you plan to add support for this tool or allow to extend it by someone else?

**Comment by dylanratcliffe** [comment]
Allowing it to be extended is definitely on the radar, having said that the code isn't amazing and will need a bit of re-work to be user extensible, which will involve time that I will not have in the next month. However with the librarian thing: Wouldn't it Just work™? Given that the Puppetfile syntax should be about the same?

**Comment by Mandos** [comment]
I will check it this weekend but Librarian use same way of manage dependencies as Bundler, Puppetfile to declare loose dependencies and Puppetfile.lock to lock it with specific version. I think, it also were some minor differences in Puppetfile between Librarian and r10k .

**Comment by dylanratcliffe** [comment]
Ah okay I see. To be honest this is the first time i've been asked about Librarian support as most of the people that I see are using r10k/code manager, have you considered moving over? I'll have a chat to rodjek tomorrow and see what he recommends.

**Comment by dylanratcliffe** [comment]
At the moment no plans to support Librarian, a good PR might change my mind though. Closing for now
