### ISSUE TITLE
--skip_r10k causes tests to run against stale copy of control-repo 

### ISSUE THREAD

**Issue by jessereynolds** [dylanratcliffe/onceover#95]
This occurred during a live demo. I was demo'ing making a syntax error in a profile class, and then correcting it. I then ran `bundle exec onceover run spec --skip_r10k` and the error did not go away. It was only until I rant it without the `--skip-r10k` that the error went away.

**Comment by jessereynolds** [comment]
Fixed in https://github.com/jessereynolds/onceover/commit/98a850be73c75667bf6cfd45cbb4b6d2cdd62e0a

**Comment by Mandos** [comment]
Shouldn't it be closed?
