### ISSUE TITLE
Permission denied when running on server where r10k has run as root

### ISSUE THREAD

**Issue by sandymcp** [dylanratcliffe/onceover#96]
Got a permission denied in /var/cache/r10k when running onceover-run-spec, because the cache was owned by root. Not really a bug I suppose, because a quick chmod -R fixes it, but might be nice to have the option to use a user level cache (or did I miss something in the docs)

**Comment by dylanratcliffe** [comment]
It's not documented but you could use r10k's config file. Onceover doesn't currently support passing a file to r10k for it to use as its config, but if you put an `r10k.yaml` in the root of the controlrepo [as documented here](https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#config-file-location), the setting you are looking for is [cachedir](https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#cachedir)

**Comment by sandymcp** [comment]
I'll try it out.

**Comment by dylanratcliffe** [comment]
Onceover may start managing r10k's cache itself as part of efforts to improve caching \, if so this will be fixed. Until that point it will have to be chmod -R
