### ISSUE TITLE
Path error on run spec

### ISSUE THREAD

**Issue by sandymcp** [dylanratcliffe/onceover#97]
Running on Windows 7 Enterprise Service Pack 1:

onceover run spec

I get 

Error while running: #<Errno::EACCES: Permission denied @ rb_file_s_symlink - (/Users/en10029/dev/control-repo/.onceover/etc/puppetlabs/code/environments/production/modules/acl, C:/Users/en10029/dev/control-repo/.onceover/spec/fixtures/modules/acl)>

because the Path to the existing file is missing a C:/. How do I fix this? Without upgrade of windows.

**Comment by sandymcp** [comment]
Work around:

onceover run spec -s --tempdir 'C:\Users\en10029\dev\control-repo\.onceover'

**Comment by dylanratcliffe** [comment]
Yeah that shouldn't happen, going into the backlog

**Comment by sandymcp** [comment]
I'll take a look at producing a patch

**Comment by tabakhase** [comment]
"target can not be inside the source" appears to be a hard limit...
given `C:/dev/control`
- `./.onceover` (default) fails
- `C:/dev/control/.onceover` fails
- `./dummy/.onceover` fails
- `C:/dev/control/dummy/.onceover` fails
- `../controll.onceover` *works*
- `C:/dev/control.onceover` *works*
- `D:/someother/control.onceover` *works*

-> the "missing driveletter" has nothing todo with it, I tested that =( 

---

```
# spec/onceover.yaml
opts:
# use with caution
  :tempdir: '../control.onceover'
```
respective 
`bundle exec` `onceover run spec --tempdir '../control.onceover'`
