### ISSUE TITLE
Puppet not reading hiera correctly when running with onceover

### ISSUE THREAD

**Issue by sandymcp** [dylanratcliffe/onceover#98]
If I run 
` hiera --debug -c .onceover/spec/hiera.yaml drdc_base`
I can find the drdc_base, but if I run onceover
`onceover run spec -d`
My tests fail with
`role::icinga_server using fact set RHEL-7-3 should compile into a catalogue without dependency cycles
      Failure/Error: it { should compile }
        error during compilation: Evaluation Error: Error while evaluating a Function Call, Could not find data item drdc_base in any Hiera data file and no default supplied at /home/en10029/control-repo/.onceover/etc/puppetlabs/code/environments/production/site/app/manifests/init.pp:17:15 on node lsv20222.linux.internalcorp.net`

Puppet runs are also fine 

Uploaded the YAML files as txt files to keep github happy

[common.txt](https://github.com/dylanratcliffe/onceover/files/1141291/common.txt)
[hiera.txt](https://github.com/dylanratcliffe/onceover/files/1141292/hiera.txt)
[onceover.txt](https://github.com/dylanratcliffe/onceover/files/1141290/onceover.txt)

**Comment by sandymcp** [comment]
Looks like it is not finding the file `common.yaml`. I put a deliberately broken yaml file there, I would expect that the hiera lookup would break. I also changed the value to "common", still no luck. Does onceover have its own yaml backend or is it using the puppet one?

**Comment by sandymcp** [comment]
I stepped through in the debugger, it looks like the yaml backend datadir value is set to a fixed value `"/home/en10029/control-repo/.onceover/etc/puppetlabs/code/environments/production/"` irrespective of the value in the hiera.yaml, which is sort of sensible as it's an absolute path within the onceover setup. Unfortunately it's not the value that is the puppet default, which expects the stuff to be in .../production/hierdata. Will the onceover run copy hierdata from the spec directory if it's at a particular location? 

`    113: def datasourcefiles(backend, scope, extension, override=nil, hierarchy=nil)
    114:   datadir = Backend.datadir(backend, scope)
 => 115:   Backend.datasources(scope, override, hierarchy) do |source|
    116:     Hiera.debug("Looking for data source #{source}")
    117:     file = datafile_in(datadir, source, extension)
    118:
    119:     if file
    120:       yield source, file
    121:     end
    122:   end
    123: end

[5] pry(Hiera::Backend)> datadir
=> "/home/en10029/control-repo/.onceover/etc/puppetlabs/code/environments/production/"
`

**Comment by dylanratcliffe** [comment]
@sandymcp The `spec/hiera.yaml` file needs to have a datadir that is relative to the root of the controlrepo i.e. just `hieradata`. Onceover won't move anything around though.

**Comment by sandymcp** [comment]
Ok so I dug around a bit more.  

If I leave out the datadir altogether, I would expect the file in
`.onceover/etc/puppetlabs/code/environments/production/hieradata/common.yaml`
to be used as the puppet documentation says that is the default. However it tries to look in 
`/etc/puppetlabs/code/environments/rp_env/hieradata`

If I put in the datadir: value but leave it empty, I would also expect the
`.onceover/etc/puppetlabs/code/environments/production/hieradata/common.yaml`
to be used as puppet looks there, but the value set by onceover is
`/home/en10029/control-repo/.onceover/etc/puppetlabs/code/environments/production/`

I get the correct value if I specifically set hieradata as the value for datadir:
`.onceover/etc/puppetlabs/code/environments/production/hieradata`

So like I said I'll punt a merge request in.

**Comment by dylanratcliffe** [comment]
Just to confirm, have you set the datadir of the hiera.yaml you are using for testing to be relative to the root of the controlrepo? It likely won't work directly from the Puppet master (depending on how you have set it up. The datadir will need to be modified as `etc/puppetlabs/code/environments/STRY0011377/hieradata` likely isn't the correct place when testing on your local machine

**Comment by sandymcp** [comment]
In the README you say the datadir should be relative to the controlrepo root, which it is: it's at the default puppet location.  What you don't say is that this value must be explicitly set to hieradata even when using the puppet default. That's what tripped me up. IMHO onceover should obey the puppet default setting when datadir is not set as I bet 99% of users the default.

**Comment by dylanratcliffe** [comment]
But the thing is the default setting isn't relative, it's `/etc/puppetlabs/code/hieradata` at least that's what [this](https://docs.puppet.com/hiera/2.0/configuring.html#yaml-and-json) says. So if it obeyed the default it would end up looking the that absolute path, which is almost definitely not right given you are likely running this in your own laptop. Maybe an error message would be better, error out of the path is not relative?

**Comment by sandymcp** [comment]
I think a statement in the README like "if your puppet master hiera.yaml does not set the datadir, because you are using the puppet default, you will need to set it explicitly to hieradata" or similar would be fine and yes an error message would be nice.

**Comment by x4FF3** [comment]
hi,
i did set the datadir to hieradata, which is located inside the controlrepo.
https://gist.github.com/x4FF3/fe6bf559f69b4c5f2f33265251c45f14
but on 
> onceover run spec
it cannot lookup any key.
